---
- hosts: webservers
  tasks:
    - name: Install nginx
      apt: pkg=nginx state=installed update_cache=true
      notify:
        - start nginx

    - name: Upload index.html
      template: src=../files/index.html.j2 dest=/usr/share/nginx/www/index.html mode=0644

    - name: Ensure nginx is running
      service: name=nginx state=started enabled=yes

  handlers:
    - name: start nginx
      service: name=nginx state=started

- hosts: loadbalancers
  tasks:
    - name: Install nginx
      apt: pkg=nginx state=installed update_cache=true

    - name: Configure nginx
      template: src=../files/nginx.conf.j2 dest=/etc/nginx/nginx.conf mode=0644
      notify:
        - restart nginx

    - name: Ensure nginx is running
      service: name=nginx state=started enabled=yes

  handlers:
    - name: restart nginx
      service: name=nginx state=restarted
